/* 
 * Aspose.Diagram Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Aspose.Diagram.Cloud.SDK.Client;
using Aspose.Diagram.Cloud.SDK.Model;

namespace Aspose.Diagram.Cloud.SDK.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDiagramApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Converts document from the request&#39;s content to the specified format.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">Download document name.</param>
        /// <param name="file">File to upload</param>
        /// <param name="sourceFilename">Source document name. (optional)</param>
        /// <returns>System.IO.Stream</returns>
        System.IO.Stream ConvertDocument (string name, System.IO.Stream file, string sourceFilename = null);

        /// <summary>
        /// Converts document from the request&#39;s content to the specified format.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">Download document name.</param>
        /// <param name="file">File to upload</param>
        /// <param name="sourceFilename">Source document name. (optional)</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        ApiResponse<System.IO.Stream> ConvertDocumentWithHttpInfo (string name, System.IO.Stream file, string sourceFilename = null);
        /// <summary>
        /// Create Empty file into the specified format.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The document name.</param>
        /// <param name="folder">The document folder. (optional)</param>
        /// <param name="isOverwrite">If true overwrite the same name file.The default value is false  (optional, default to false)</param>
        /// <returns>CreateNewResponse</returns>
        CreateNewResponse CreateNew (string name, string folder = null, bool? isOverwrite = null);

        /// <summary>
        /// Create Empty file into the specified format.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The document name.</param>
        /// <param name="folder">The document folder. (optional)</param>
        /// <param name="isOverwrite">If true overwrite the same name file.The default value is false  (optional, default to false)</param>
        /// <returns>ApiResponse of CreateNewResponse</returns>
        ApiResponse<CreateNewResponse> CreateNewWithHttpInfo (string name, string folder = null, bool? isOverwrite = null);
        /// <summary>
        /// Exports the document into the specified format.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The document name.</param>
        /// <param name="format">The destination format.</param>
        /// <param name="folder">Original document folder. (optional)</param>
        /// <returns>System.IO.Stream</returns>
        System.IO.Stream DownloadFileWithFormat (string name, string format, string folder = null);

        /// <summary>
        /// Exports the document into the specified format.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The document name.</param>
        /// <param name="format">The destination format.</param>
        /// <param name="folder">Original document folder. (optional)</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        ApiResponse<System.IO.Stream> DownloadFileWithFormatWithHttpInfo (string name, string format, string folder = null);
        /// <summary>
        /// Converts document to destination format with detailed settings and saves result to storage.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">Original document name.</param>
        /// <param name="saveOptionsRequest">Save options.</param>
        /// <param name="folder">Original document folder. (optional)</param>
        /// <param name="isOverwrite">If true overwrite the same name file.The default value is false  (optional, default to false)</param>
        /// <returns>SaveAsResponse</returns>
        SaveAsResponse SaveAs (string name, SaveOptionsRequest saveOptionsRequest, string folder = null, bool? isOverwrite = null);

        /// <summary>
        /// Converts document to destination format with detailed settings and saves result to storage.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">Original document name.</param>
        /// <param name="saveOptionsRequest">Save options.</param>
        /// <param name="folder">Original document folder. (optional)</param>
        /// <param name="isOverwrite">If true overwrite the same name file.The default value is false  (optional, default to false)</param>
        /// <returns>ApiResponse of SaveAsResponse</returns>
        ApiResponse<SaveAsResponse> SaveAsWithHttpInfo (string name, SaveOptionsRequest saveOptionsRequest, string folder = null, bool? isOverwrite = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Converts document from the request&#39;s content to the specified format.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">Download document name.</param>
        /// <param name="file">File to upload</param>
        /// <param name="sourceFilename">Source document name. (optional)</param>
        /// <returns>Task of System.IO.Stream</returns>
        System.Threading.Tasks.Task<System.IO.Stream> ConvertDocumentAsync (string name, System.IO.Stream file, string sourceFilename = null);

        /// <summary>
        /// Converts document from the request&#39;s content to the specified format.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">Download document name.</param>
        /// <param name="file">File to upload</param>
        /// <param name="sourceFilename">Source document name. (optional)</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> ConvertDocumentAsyncWithHttpInfo (string name, System.IO.Stream file, string sourceFilename = null);
        /// <summary>
        /// Create Empty file into the specified format.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The document name.</param>
        /// <param name="folder">The document folder. (optional)</param>
        /// <param name="isOverwrite">If true overwrite the same name file.The default value is false  (optional, default to false)</param>
        /// <returns>Task of CreateNewResponse</returns>
        System.Threading.Tasks.Task<CreateNewResponse> CreateNewAsync (string name, string folder = null, bool? isOverwrite = null);

        /// <summary>
        /// Create Empty file into the specified format.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The document name.</param>
        /// <param name="folder">The document folder. (optional)</param>
        /// <param name="isOverwrite">If true overwrite the same name file.The default value is false  (optional, default to false)</param>
        /// <returns>Task of ApiResponse (CreateNewResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreateNewResponse>> CreateNewAsyncWithHttpInfo (string name, string folder = null, bool? isOverwrite = null);
        /// <summary>
        /// Exports the document into the specified format.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The document name.</param>
        /// <param name="format">The destination format.</param>
        /// <param name="folder">Original document folder. (optional)</param>
        /// <returns>Task of System.IO.Stream</returns>
        System.Threading.Tasks.Task<System.IO.Stream> DownloadFileWithFormatAsync (string name, string format, string folder = null);

        /// <summary>
        /// Exports the document into the specified format.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The document name.</param>
        /// <param name="format">The destination format.</param>
        /// <param name="folder">Original document folder. (optional)</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> DownloadFileWithFormatAsyncWithHttpInfo (string name, string format, string folder = null);
        /// <summary>
        /// Converts document to destination format with detailed settings and saves result to storage.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">Original document name.</param>
        /// <param name="saveOptionsRequest">Save options.</param>
        /// <param name="folder">Original document folder. (optional)</param>
        /// <param name="isOverwrite">If true overwrite the same name file.The default value is false  (optional, default to false)</param>
        /// <returns>Task of SaveAsResponse</returns>
        System.Threading.Tasks.Task<SaveAsResponse> SaveAsAsync (string name, SaveOptionsRequest saveOptionsRequest, string folder = null, bool? isOverwrite = null);

        /// <summary>
        /// Converts document to destination format with detailed settings and saves result to storage.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">Original document name.</param>
        /// <param name="saveOptionsRequest">Save options.</param>
        /// <param name="folder">Original document folder. (optional)</param>
        /// <param name="isOverwrite">If true overwrite the same name file.The default value is false  (optional, default to false)</param>
        /// <returns>Task of ApiResponse (SaveAsResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SaveAsResponse>> SaveAsAsyncWithHttpInfo (string name, SaveOptionsRequest saveOptionsRequest, string folder = null, bool? isOverwrite = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DiagramApi : IDiagramApi
    {
        private Aspose.Diagram.Cloud.SDK.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DiagramApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DiagramApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = Aspose.Diagram.Cloud.SDK.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }
		
		/// <summary>
        /// Initializes a new instance of the <see cref="DiagramApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DiagramApi(String basePath, String accesstoken)
        {
            Dictionary<string, string> headerParameters = new Dictionary<string, string>();
            headerParameters.Add("Authorization", "Bearer " + accesstoken);
            this.Configuration = new Configuration(new ApiClient(basePath),headerParameters);

            ExceptionFactory = Aspose.Diagram.Cloud.SDK.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DiagramApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DiagramApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Aspose.Diagram.Cloud.SDK.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }
		
		/// <summary>
        /// Initializes a new instance of the <see cref="DiagramApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DiagramApi(String grantType,String appSID,String appKey)
        {
            OAuthApi oauth2 = new OAuthApi("https://api.aspose.cloud");
            var oauth2response = oauth2.OAuthPost(grantType, appSID, appKey);
            Dictionary<string, string> headerParameters = new Dictionary<string, string>();
            headerParameters.Add("Authorization", "Bearer " + oauth2response.AccessToken);
            this.Configuration =  new Configuration(new ApiClient(), headerParameters);
            ExceptionFactory = Aspose.Diagram.Cloud.SDK.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Aspose.Diagram.Cloud.SDK.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Converts document from the request&#39;s content to the specified format. 
        /// </summary>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">Download document name.</param>
        /// <param name="file">File to upload</param>
        /// <param name="sourceFilename">Source document name. (optional)</param>
        /// <returns>System.IO.Stream</returns>
        public System.IO.Stream ConvertDocument (string name, System.IO.Stream file, string sourceFilename = null)
        {
             ApiResponse<System.IO.Stream> localVarResponse = ConvertDocumentWithHttpInfo(name, file, sourceFilename);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Converts document from the request&#39;s content to the specified format. 
        /// </summary>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">Download document name.</param>
        /// <param name="file">File to upload</param>
        /// <param name="sourceFilename">Source document name. (optional)</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        public ApiResponse< System.IO.Stream > ConvertDocumentWithHttpInfo (string name, System.IO.Stream file, string sourceFilename = null)
        {
            // verify the required parameter 'name' is set
            if (name == null)
                throw new ApiException(400, "Missing required parameter 'name' when calling DiagramApi->ConvertDocument");
            // verify the required parameter 'file' is set
            if (file == null)
                throw new ApiException(400, "Missing required parameter 'file' when calling DiagramApi->ConvertDocument");

            var localVarPath = "/diagram/{name}/convert";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "multipart/form-data"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (name != null) localVarPathParams.Add("name", Configuration.ApiClient.ParameterToString(name)); // path parameter
            if (sourceFilename != null) localVarQueryParams.Add("sourceFilename", Configuration.ApiClient.ParameterToString(sourceFilename)); // query parameter
            if (file != null) localVarFileParams.Add("File", Configuration.ApiClient.ParameterToFile("File", file));

            // authentication (JWT) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ConvertDocument", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

        /// <summary>
        /// Converts document from the request&#39;s content to the specified format. 
        /// </summary>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">Download document name.</param>
        /// <param name="file">File to upload</param>
        /// <param name="sourceFilename">Source document name. (optional)</param>
        /// <returns>Task of System.IO.Stream</returns>
        public async System.Threading.Tasks.Task<System.IO.Stream> ConvertDocumentAsync (string name, System.IO.Stream file, string sourceFilename = null)
        {
             ApiResponse<System.IO.Stream> localVarResponse = await ConvertDocumentAsyncWithHttpInfo(name, file, sourceFilename);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Converts document from the request&#39;s content to the specified format. 
        /// </summary>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">Download document name.</param>
        /// <param name="file">File to upload</param>
        /// <param name="sourceFilename">Source document name. (optional)</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> ConvertDocumentAsyncWithHttpInfo (string name, System.IO.Stream file, string sourceFilename = null)
        {
            // verify the required parameter 'name' is set
            if (name == null)
                throw new ApiException(400, "Missing required parameter 'name' when calling DiagramApi->ConvertDocument");
            // verify the required parameter 'file' is set
            if (file == null)
                throw new ApiException(400, "Missing required parameter 'file' when calling DiagramApi->ConvertDocument");

            var localVarPath = "/diagram/{name}/convert";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "multipart/form-data"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (name != null) localVarPathParams.Add("name", Configuration.ApiClient.ParameterToString(name)); // path parameter
            if (sourceFilename != null) localVarQueryParams.Add("sourceFilename", Configuration.ApiClient.ParameterToString(sourceFilename)); // query parameter
            if (file != null) localVarFileParams.Add("File", Configuration.ApiClient.ParameterToFile("File", file));

            // authentication (JWT) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ConvertDocument", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

        /// <summary>
        /// Create Empty file into the specified format. 
        /// </summary>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The document name.</param>
        /// <param name="folder">The document folder. (optional)</param>
        /// <param name="isOverwrite">If true overwrite the same name file.The default value is false  (optional, default to false)</param>
        /// <returns>CreateNewResponse</returns>
        public CreateNewResponse CreateNew (string name, string folder = null, bool? isOverwrite = null)
        {
             ApiResponse<CreateNewResponse> localVarResponse = CreateNewWithHttpInfo(name, folder, isOverwrite);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create Empty file into the specified format. 
        /// </summary>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The document name.</param>
        /// <param name="folder">The document folder. (optional)</param>
        /// <param name="isOverwrite">If true overwrite the same name file.The default value is false  (optional, default to false)</param>
        /// <returns>ApiResponse of CreateNewResponse</returns>
        public ApiResponse< CreateNewResponse > CreateNewWithHttpInfo (string name, string folder = null, bool? isOverwrite = null)
        {
            // verify the required parameter 'name' is set
            if (name == null)
                throw new ApiException(400, "Missing required parameter 'name' when calling DiagramApi->CreateNew");

            var localVarPath = "/diagram/{name}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (name != null) localVarPathParams.Add("name", Configuration.ApiClient.ParameterToString(name)); // path parameter
            if (folder != null) localVarQueryParams.Add("folder", Configuration.ApiClient.ParameterToString(folder)); // query parameter
            if (isOverwrite != null) localVarQueryParams.Add("IsOverwrite", Configuration.ApiClient.ParameterToString(isOverwrite)); // query parameter

            // authentication (JWT) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateNew", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CreateNewResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (CreateNewResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(CreateNewResponse)));
        }

        /// <summary>
        /// Create Empty file into the specified format. 
        /// </summary>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The document name.</param>
        /// <param name="folder">The document folder. (optional)</param>
        /// <param name="isOverwrite">If true overwrite the same name file.The default value is false  (optional, default to false)</param>
        /// <returns>Task of CreateNewResponse</returns>
        public async System.Threading.Tasks.Task<CreateNewResponse> CreateNewAsync (string name, string folder = null, bool? isOverwrite = null)
        {
             ApiResponse<CreateNewResponse> localVarResponse = await CreateNewAsyncWithHttpInfo(name, folder, isOverwrite);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create Empty file into the specified format. 
        /// </summary>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The document name.</param>
        /// <param name="folder">The document folder. (optional)</param>
        /// <param name="isOverwrite">If true overwrite the same name file.The default value is false  (optional, default to false)</param>
        /// <returns>Task of ApiResponse (CreateNewResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<CreateNewResponse>> CreateNewAsyncWithHttpInfo (string name, string folder = null, bool? isOverwrite = null)
        {
            // verify the required parameter 'name' is set
            if (name == null)
                throw new ApiException(400, "Missing required parameter 'name' when calling DiagramApi->CreateNew");

            var localVarPath = "/diagram/{name}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (name != null) localVarPathParams.Add("name", Configuration.ApiClient.ParameterToString(name)); // path parameter
            if (folder != null) localVarQueryParams.Add("folder", Configuration.ApiClient.ParameterToString(folder)); // query parameter
            if (isOverwrite != null) localVarQueryParams.Add("IsOverwrite", Configuration.ApiClient.ParameterToString(isOverwrite)); // query parameter

            // authentication (JWT) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateNew", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CreateNewResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (CreateNewResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(CreateNewResponse)));
        }

        /// <summary>
        /// Exports the document into the specified format. 
        /// </summary>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The document name.</param>
        /// <param name="format">The destination format.</param>
        /// <param name="folder">Original document folder. (optional)</param>
        /// <returns>System.IO.Stream</returns>
        public System.IO.Stream DownloadFileWithFormat (string name, string format, string folder = null)
        {
             ApiResponse<System.IO.Stream> localVarResponse = DownloadFileWithFormatWithHttpInfo(name, format, folder);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Exports the document into the specified format. 
        /// </summary>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The document name.</param>
        /// <param name="format">The destination format.</param>
        /// <param name="folder">Original document folder. (optional)</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        public ApiResponse< System.IO.Stream > DownloadFileWithFormatWithHttpInfo (string name, string format, string folder = null)
        {
            // verify the required parameter 'name' is set
            if (name == null)
                throw new ApiException(400, "Missing required parameter 'name' when calling DiagramApi->DownloadFileWithFormat");
            // verify the required parameter 'format' is set
            if (format == null)
                throw new ApiException(400, "Missing required parameter 'format' when calling DiagramApi->DownloadFileWithFormat");

            var localVarPath = "/diagram/{name}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "multipart/form-data"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (name != null) localVarPathParams.Add("name", Configuration.ApiClient.ParameterToString(name)); // path parameter
            if (format != null) localVarQueryParams.Add("format", Configuration.ApiClient.ParameterToString(format)); // query parameter
            if (folder != null) localVarQueryParams.Add("folder", Configuration.ApiClient.ParameterToString(folder)); // query parameter

            // authentication (JWT) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DownloadFileWithFormat", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

        /// <summary>
        /// Exports the document into the specified format. 
        /// </summary>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The document name.</param>
        /// <param name="format">The destination format.</param>
        /// <param name="folder">Original document folder. (optional)</param>
        /// <returns>Task of System.IO.Stream</returns>
        public async System.Threading.Tasks.Task<System.IO.Stream> DownloadFileWithFormatAsync (string name, string format, string folder = null)
        {
             ApiResponse<System.IO.Stream> localVarResponse = await DownloadFileWithFormatAsyncWithHttpInfo(name, format, folder);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Exports the document into the specified format. 
        /// </summary>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The document name.</param>
        /// <param name="format">The destination format.</param>
        /// <param name="folder">Original document folder. (optional)</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> DownloadFileWithFormatAsyncWithHttpInfo (string name, string format, string folder = null)
        {
            // verify the required parameter 'name' is set
            if (name == null)
                throw new ApiException(400, "Missing required parameter 'name' when calling DiagramApi->DownloadFileWithFormat");
            // verify the required parameter 'format' is set
            if (format == null)
                throw new ApiException(400, "Missing required parameter 'format' when calling DiagramApi->DownloadFileWithFormat");

            var localVarPath = "/diagram/{name}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "multipart/form-data"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (name != null) localVarPathParams.Add("name", Configuration.ApiClient.ParameterToString(name)); // path parameter
            if (format != null) localVarQueryParams.Add("format", Configuration.ApiClient.ParameterToString(format)); // query parameter
            if (folder != null) localVarQueryParams.Add("folder", Configuration.ApiClient.ParameterToString(folder)); // query parameter

            // authentication (JWT) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DownloadFileWithFormat", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
        }

        /// <summary>
        /// Converts document to destination format with detailed settings and saves result to storage. 
        /// </summary>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">Original document name.</param>
        /// <param name="saveOptionsRequest">Save options.</param>
        /// <param name="folder">Original document folder. (optional)</param>
        /// <param name="isOverwrite">If true overwrite the same name file.The default value is false  (optional, default to false)</param>
        /// <returns>SaveAsResponse</returns>
        public SaveAsResponse SaveAs (string name, SaveOptionsRequest saveOptionsRequest, string folder = null, bool? isOverwrite = null)
        {
             ApiResponse<SaveAsResponse> localVarResponse = SaveAsWithHttpInfo(name, saveOptionsRequest, folder, isOverwrite);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Converts document to destination format with detailed settings and saves result to storage. 
        /// </summary>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">Original document name.</param>
        /// <param name="saveOptionsRequest">Save options.</param>
        /// <param name="folder">Original document folder. (optional)</param>
        /// <param name="isOverwrite">If true overwrite the same name file.The default value is false  (optional, default to false)</param>
        /// <returns>ApiResponse of SaveAsResponse</returns>
        public ApiResponse< SaveAsResponse > SaveAsWithHttpInfo (string name, SaveOptionsRequest saveOptionsRequest, string folder = null, bool? isOverwrite = null)
        {
            // verify the required parameter 'name' is set
            if (name == null)
                throw new ApiException(400, "Missing required parameter 'name' when calling DiagramApi->SaveAs");
            // verify the required parameter 'saveOptionsRequest' is set
            if (saveOptionsRequest == null)
                throw new ApiException(400, "Missing required parameter 'saveOptionsRequest' when calling DiagramApi->SaveAs");

            var localVarPath = "/diagram/{name}/saveAs";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (name != null) localVarPathParams.Add("name", Configuration.ApiClient.ParameterToString(name)); // path parameter
            if (folder != null) localVarQueryParams.Add("folder", Configuration.ApiClient.ParameterToString(folder)); // query parameter
            if (isOverwrite != null) localVarQueryParams.Add("IsOverwrite", Configuration.ApiClient.ParameterToString(isOverwrite)); // query parameter
            if (saveOptionsRequest != null && saveOptionsRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(saveOptionsRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = saveOptionsRequest; // byte array
            }

            // authentication (JWT) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SaveAs", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SaveAsResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (SaveAsResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(SaveAsResponse)));
        }

        /// <summary>
        /// Converts document to destination format with detailed settings and saves result to storage. 
        /// </summary>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">Original document name.</param>
        /// <param name="saveOptionsRequest">Save options.</param>
        /// <param name="folder">Original document folder. (optional)</param>
        /// <param name="isOverwrite">If true overwrite the same name file.The default value is false  (optional, default to false)</param>
        /// <returns>Task of SaveAsResponse</returns>
        public async System.Threading.Tasks.Task<SaveAsResponse> SaveAsAsync (string name, SaveOptionsRequest saveOptionsRequest, string folder = null, bool? isOverwrite = null)
        {
             ApiResponse<SaveAsResponse> localVarResponse = await SaveAsAsyncWithHttpInfo(name, saveOptionsRequest, folder, isOverwrite);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Converts document to destination format with detailed settings and saves result to storage. 
        /// </summary>
        /// <exception cref="Aspose.Diagram.Cloud.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">Original document name.</param>
        /// <param name="saveOptionsRequest">Save options.</param>
        /// <param name="folder">Original document folder. (optional)</param>
        /// <param name="isOverwrite">If true overwrite the same name file.The default value is false  (optional, default to false)</param>
        /// <returns>Task of ApiResponse (SaveAsResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SaveAsResponse>> SaveAsAsyncWithHttpInfo (string name, SaveOptionsRequest saveOptionsRequest, string folder = null, bool? isOverwrite = null)
        {
            // verify the required parameter 'name' is set
            if (name == null)
                throw new ApiException(400, "Missing required parameter 'name' when calling DiagramApi->SaveAs");
            // verify the required parameter 'saveOptionsRequest' is set
            if (saveOptionsRequest == null)
                throw new ApiException(400, "Missing required parameter 'saveOptionsRequest' when calling DiagramApi->SaveAs");

            var localVarPath = "/diagram/{name}/saveAs";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (name != null) localVarPathParams.Add("name", Configuration.ApiClient.ParameterToString(name)); // path parameter
            if (folder != null) localVarQueryParams.Add("folder", Configuration.ApiClient.ParameterToString(folder)); // query parameter
            if (isOverwrite != null) localVarQueryParams.Add("IsOverwrite", Configuration.ApiClient.ParameterToString(isOverwrite)); // query parameter
            if (saveOptionsRequest != null && saveOptionsRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(saveOptionsRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = saveOptionsRequest; // byte array
            }

            // authentication (JWT) required
            // oauth required
            if (!String.IsNullOrEmpty(Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SaveAs", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SaveAsResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (SaveAsResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(SaveAsResponse)));
        }

    }
}
